#!/bin/bash
#author: gobonja

readonly CONF_FILE=/etc/timeshift-autosnap.conf
readonly SNAPSHOTS_TO_DELETE=/tmp/timeshift-autosnap-tmp

readonly SNAPSHOT_NAME_PATTERN="[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_[0-9]\{2\}-[0-9]\{2\}-[0-9]\{2\}"
readonly SNAPSHOT_DESCRIPTION="{timeshift-autosnap} {created before upgrade}"

function get_property() {
    if [ ! -f $CONF_FILE ]; then
        echo "$CONF_FILE not found! Using $1=$3" >&2;
        param_value=$3
    else
        param_value=`sed '/^\#/d' $CONF_FILE | grep $1 | tail -n 1 |\
        cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`

        if ([ $2 == "boolean" ] && [ $param_value != true ] && [ $param_value != false ]) || \
           ([ $2 == "integer" ] && [[ ! $param_value =~ ^[-+]?([1-9][[:digit:]]*|1)$ ]]) ; then
            echo "Wrong paramater in $CONF_FILE. Using $1=$3" >&2
            param_value=$3
        fi
    fi

    echo $param_value
}

if $(get_property "skipAutosnap" "boolean" "false") ; then
    echo "==> skipping timeshift-autosnap due skipAutosnap in $CONF_FILE set to TRUE." >&2; exit 0;
fi

timeshift --create --comments "$SNAPSHOT_DESCRIPTION" || { echo "Please close Timeshift and try again. Script will now exit..." >&2; exit 1; }

if $(get_property "deleteSnapshots" "boolean" "true") ; then
    timeshift --list > $SNAPSHOTS_TO_DELETE
    sed -ni "/$SNAPSHOT_DESCRIPTION/p" $SNAPSHOTS_TO_DELETE
    sed -ni "s/.*\($SNAPSHOT_NAME_PATTERN\).*/\1/p" $SNAPSHOTS_TO_DELETE

    count=$(($(sed -n '$=' $SNAPSHOTS_TO_DELETE)-$(get_property "maxSnapshots" "integer" "3")))

    if [ $count -gt 0 ] ; then
        sed -i $(($count))q $SNAPSHOTS_TO_DELETE
        
        for snapshot in $(cat $SNAPSHOTS_TO_DELETE); do
            timeshift --delete --snapshot $snapshot
        done
    fi
fi;

if $(get_property "updateGrub" "boolean" "true") && [ "$(pacman -Qs ^grub-btrfs$)" ]; then
    grub-mkconfig -o /boot/grub/grub.cfg
fi;

exit 0